version: 2.1

executors:
  go-executor:
    docker:
      - image: cimg/go:1.20.2
    working_directory: ~/repo/toi-scraper-go

jobs:
  build:
    executor: go-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Build the go program
          command: go build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - toi-scraper-go
  test:
    executor: go-executor
    steps:
      - attach_workspace:
          at: ~/repo/
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - store_test_results:
          path: /tmp/test-reports
  deploy:
    machine:
      image: "ubuntu-2004:current"
    working_directory: ~/repo/toi-scraper-go
    steps:
      - attach_workspace:
            at: ~/repo/
      - run:
            name: Deploy over SSH to whatbox
            command: scp ./toi-scraper $SSH_USER@$SSH_HOST:/home/shyamsundar2007/bin/
      - run:
            name: Setup env vars
            command: |
              if ssh $SSH_USER@$SSH_HOST "grep 'export TELEGRAM_APITOKEN' ~/.zshrc"; then
                echo 'Overwriting TELEGRAM_APITOKEN to ~/.zshrc'
                sed_command="s/^export TELEGRAM_APITOKEN=.*/export TELEGRAM_APITOKEN=$TELEGRAM_APITOKEN/"
                ssh $SSH_USER@$SSH_HOST "sed -i '$sed_command' ~/.zshrc"
              else
                echo 'Writing TELEGRAM_APITOKEN to ~/.zshrc'
                ssh $SSH_USER@$SSH_HOST "echo 'export TELEGRAM_APITOKEN=$TELEGRAM_APITOKEN' >> ~/.zshrc"
              fi
              ssh $SSH_USER@$SSH_HOST 'source ~/.zshrc'
      - run:
          name: Setup chat ID
          command: |
            if ssh $SSH_USER@$SSH_HOST "grep 'export TOI_CHAT_ID' ~/.zshrc"; then
              echo 'Overwriting TOI_CHAT_ID to ~/.zshrc'
              sed_command="s/^export TOI_CHAT_ID=.*/export TOI_CHAT_ID=$TOI_CHAT_ID/"
              ssh $SSH_USER@$SSH_HOST "sed -i '$sed_command' ~/.zshrc"
            else
              echo 'Writing TOI_CHAT_ID to ~/.zshrc'
              ssh $SSH_USER@$SSH_HOST "echo 'export TOI_CHAT_ID=$TOI_CHAT_ID' >> ~/.zshrc"
            fi
            ssh $SSH_USER@$SSH_HOST 'source ~/.zshrc'
workflows:
  build-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: main