version: 2.1

executors:
  go-executor:
    docker:
      - image: cimg/go:1.20.2
    working_directory: ~/repo/toi-scraper-go

jobs:
  build:
    executor: go-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Build the go program
          command: go build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - toi-scraper-go
  test:
    executor: go-executor
    steps:
      - attach_workspace:
          at: ~/repo/
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - store_test_results:
          path: /tmp/test-reports
  deploy:
    machine:
      image: "ubuntu-2004:current"
    working_directory: ~/repo/toi-scraper-go
    steps:
      - attach_workspace:
            at: ~/repo/
      - run:
            name: Deploy over SSH to whatbox
            command: |
              pwd
              ls -lsh
              scp ./toi-scraper $SSH_USER@$SSH_HOST:/home/shyamsundar2007/bin/
workflows:
  build-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: main